---
meta:
  name:    gobetween
  release: gobetween
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 0.3.0

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: nomad-warden

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   gobetween-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/gobetween-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/gobetween-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/gobetween-boshrelease/slack:webhook" ))
    channel: '#botspam'
